apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent-role-binding
subjects:
- kind: ServiceAccount
  name: agent-sa
  namespace: test
roleRef:
  kind: ClusterRole
  name: agent-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deployment
  labels:
    app: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      # imagePullPolicy: ifNotPresent
      serviceAccountName: agent-sa
      containers:
      - name: agent
        image: dotruong1910/agent:test2
        ports:
        - containerPort: 9000


